version: '3.8'

networks:
  my-network:
    driver: bridge

volumes:
  prometheus_data:
    driver: local

  grafana_data:
    driver: local

services:
  api:
    build: .
    ports:
      - "7331:7331"
    networks:
      - my-network

  prometheus:
    container_name: prometheus
    image: prom/prometheus
    restart: always
    volumes:
      - ./observability/prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
    networks:
      - my-network

  alertmanager:
    container_name: alertmanager
    image: prom/alertmanager
    restart: always
    networks:
      - my-network

  node_exporter:
    container_name: node_exporter
    image: quay.io/prometheus/node-exporter:latest
    networks:
      - my-network

  grafana:
    container_name: grafana
    image: cgr.dev/chainguard/grafana
    restart: always
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=memude42
    volumes:
      - grafana_data:/var/lib/grafana
      - ./observability/camptocamp-prometheus-alertmanager-datasource:/var/lib/grafana/plugins/camptocamp-prometheus-alertmanager-datasource/
      - ./observability/datasource/datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml
      - ./observability/dashboards/dashboard-cadvisor.json:/var/lib/grafana/dashboards/dashboard-cadvisor.json
      - ./observability/dashboards/dashboard-nodeexporter.json:/var/lib/grafana/dashboards/dashboard-nodeexporter.json
      - ./observability/dashboards/dashboard-cockpit.json:/var/lib/grafana/dashboards/dashboard-cockpit.json
    networks:
      - my-network

  cadvisor:
    container_name: cadvisor
    image: cgr.dev/chainguard/cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - my-network

  locust:
    container_name: locust
    image: locustio/locust
    command: -f /mnt/locust/locustfile.py --host=http://api:7331
    volumes:
      - ./observability/locust:/mnt/locust
    networks:
      - my-network

  nginx:
    container_name: nginx
    image: nginx
    restart: always
    depends_on:
      - grafana
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./observability/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./observability/nginx/server.crt:/etc/nginx/certs/server.crt
      - ./observability/nginx/server.key:/etc/nginx/certs/server.key
    networks:
      - my-network